name: main
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - make lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - make build
      - make install
      - hello